language: python

python:
  - '3.6'
branches:
  only:
  - master

install:
- sudo apt-get update

script:
- python3 setup.py install
- pytest

deploy:
  provider: pypi
  user: Hoohm
  on:
    tags: true
  password:
    secure: n4xDXvUO5kQFvcnW2yNSbheGNC4p59dx867B+3PehgheKJAgPswsGNDTLJfTFwbxnLwwprj9/dZCtLyQo5jBhxyK5Gmp2/YzFFvZ27cPbZkQOyIpD+o+bMFvDtA9FM5M8sHvtPw54SLfGsR6TdfC9ys9LkUpGLy6tXHsy3HgVRA9nPQz2+gNVPiFfG+cIGpYHG0XWnCUDLy0C+Y+zOjQO1WJMHqCTkATZAAfnhpafAD2HVPx4qrBgn3is778DpIImmrRtn1RlTd//njmkQYw8OYvnOVsq4iaw3oL/48jRP8B7SE7PugduCRtv5Xp/vKw4MIFTg4r6hYsuVPg3Lgl0moe3YmBvxrOaEuNeFOL0g63IhwEyqYq793Aq1HtcKQMZip+cGDTpSPcksYJx+MVTzYEKJCupZ71YGt4ljY03Is22NGGwhDmoAftaC+tl/WykKcaNu/xo/ww/qQAj7Q5cHs2BBRX5SJ7kw1SFBiyGF3MCbYtTtEqxPP1x07tYrrGeegFu3hQw6XiQqU8MkROcBUHNEl1Oal4SPrQqhY4MrSFIo8Ba91ST7QbZ5M26wnXOaYaeUvMSESgvZxX2ZhLm2R33Z3P2ZC+bBOSUKQ28La15GfW9hhhpxTmgw1jzw9cimvQepN16Spza8N0RM1b5WCNAoRFxGHBHt/dXsgo9HY=
