site_name: Cite-seq-Count
theme: readthedocs
repo_name: 'GitHub'
repo_url: https://github.com/Hoohm/citeseqcount
nav:
  - 'index.md'
  - 'Installation.md'
  - 'Running-the-script.md'
  - 'Reading-the-output.md'
  - 'Guidelines.md'